import { Card, CardColor, CardType } from '../types';
import { COLOR_LABELS, COLOR_HEX, RENT_VALUES, MAX_IN_SET } from './deck';

export interface CardCatalogItem {
  id: string;
  card: Card;
  category: 'property' | 'action' | 'wildcard' | 'rent' | 'money';
  countInDeck: number;
  categoryLabelTr: string;
  categoryLabelEn: string;
  detailedDescriptionTr: string;
  detailedDescriptionEn: string;
  strategyTipsTr: string[];
  strategyTipsEn: string[];
  counterplayTr: string;
  counterplayEn: string;
  rarity: 'common' | 'rare' | 'epic' | 'legendary';
}

export const ALL_CATALOG_CARDS: CardCatalogItem[] = [
  // ==========================================
  // 1. ARSA KARTLARI (28 Adet)
  // ==========================================
  // KAHVERENGİ (Brown)
  {
    id: 'prop-baltic',
    card: {
      id: 'cat-baltic',
      type: 'property',
      name: 'Baltic Avenue',
      value: 1,
      color: 'brown',
      rentValues: [1, 2],
      maxInSet: 2,
      description: 'Kahverengi grubuna ait arsa kartı. Seti tamamlamak için 2 kart gerekir.',
    },
    category: 'property',
    countInDeck: 1,
    categoryLabelTr: 'Arsa Mülk Kartı',
    categoryLabelEn: 'Property Deed',
    detailedDescriptionTr: 'Baltic Avenue (Kasımpaşa), en ucuz arsa setlerinden biridir. Sadece 2 kart ile tam set tamamlanarak hızlı zafer puanı sağlar.',
    detailedDescriptionEn: 'Baltic Avenue is part of the Brown set. Requires only 2 cards to complete a full monopoly set.',
    strategyTipsTr: [
      'Sadece 2 kart gerektiği için oyunu en hızlı bitirme stratejilerinde anahtar rol oynar.',
      'Düşük banka değeri (1M) nedeniyle borç ödemelerinde ilk feda edilecek mülklerdendir.',
      'Ev veya Otel ekleyerek kirayı 2M\'den 5M veya 9M\'e çıkarabilirsiniz.'
    ],
    strategyTipsEn: [
      'Requires only 2 cards, making it one of the quickest sets to finish a 3-set victory condition.',
      'With low value (1M), it is safe to sacrifice for small rent debts if not close to completion.',
      'Add a House or Hotel to boost rent from 2M up to 5M or 9M!'
    ],
    counterplayTr: 'Sinsi Anlaşma (Sly Deal) ile çalın veya tamamlandığında Anlaşma Bozan (Deal Breaker) ile tamamını ele geçirin.',
    counterplayEn: 'Steal with Sly Deal before completion or take the whole set with Deal Breaker.',
    rarity: 'common',
  },
  {
    id: 'prop-mediterranean',
    card: {
      id: 'cat-mediterranean',
      type: 'property',
      name: 'Mediterranean Avenue',
      value: 1,
      color: 'brown',
      rentValues: [1, 2],
      maxInSet: 2,
      description: 'Kahverengi grubuna ait arsa kartı. Seti tamamlamak için 2 kart gerekir.',
    },
    category: 'property',
    countInDeck: 1,
    categoryLabelTr: 'Arsa Mülk Kartı',
    categoryLabelEn: 'Property Deed',
    detailedDescriptionTr: 'Mediterranean Avenue (Sultanahmet), Kahverengi setin diğer yarısıdır. Hızlı tamamlanması rakipler üzerinde baskı yaratır.',
    detailedDescriptionEn: 'Mediterranean Avenue completes the Brown set with Baltic Avenue. Quick to form a full set.',
    strategyTipsTr: [
      'Kahverengi seti erken tamamlayıp üzerine Ev kurarak erken safhada rakiplerin parasını tüketin.',
      'Zoraki Takas (Forced Deal) ile elinizdeki tekli mülkü rakibin son Kahverengisiyle takas edin.'
    ],
    strategyTipsEn: [
      'Complete the Brown set early to build a House and drain early game cash from opponents.',
      'Use Forced Deal to swap a lone property for the opponent\'s missing Brown.'
    ],
    counterplayTr: 'Rakip seti tamamlamadan önce Sinsi Anlaşma ile kartı kapın.',
    counterplayEn: 'Use Sly Deal to seize it before the set is completed.',
    rarity: 'common',
  },

  // KOYU MAVİ (Dark Blue)
  {
    id: 'prop-boardwalk',
    card: {
      id: 'cat-boardwalk',
      type: 'property',
      name: 'Boardwalk',
      value: 4,
      color: 'darkblue',
      rentValues: [3, 8],
      maxInSet: 2,
      description: 'Koyu Mavi grubuna ait efsanevi arsa kartı. 2 kartla tam set olur ve devasa kira (8M) getirir.',
    },
    category: 'property',
    countInDeck: 1,
    categoryLabelTr: 'Değerli Arsa Kartı',
    categoryLabelEn: 'Luxury Property',
    detailedDescriptionTr: 'Boardwalk (Tarabya), oyundaki en yüksek kira getirisine (8M) sahip 2 kartlık prestijli Koyu Mavi mülktür.',
    detailedDescriptionEn: 'Boardwalk has the highest base set rent in the game (8M). 2 cards complete the set.',
    strategyTipsTr: [
      'Tamamlandığında Kirayı İkiye Katla (Double Rent) ile tek hamlede 16M (ev ile 22M) talep ederek rakipleri iflas ettirebilirsiniz.',
      'Anlaşma Bozan (Deal Breaker) hedeflerinin başında gelir; elinizde Just Say No yokken masaya indirmeyin.'
    ],
    strategyTipsEn: [
      'With Double Rent, you can collect 16M+ in a single action, completely wiping out opponents.',
      'Prime target for Deal Breaker; hold it in hand until you have a Just Say No ready.'
    ],
    counterplayTr: 'Anlaşma Bozan (Deal Breaker) ile tamamlanmış Koyu Mavi setini çalmak oyunu anında lehinize çevirir.',
    counterplayEn: 'Steal the completed Dark Blue set with Deal Breaker to swing the game instantly.',
    rarity: 'legendary',
  },
  {
    id: 'prop-park-place',
    card: {
      id: 'cat-park-place',
      type: 'property',
      name: 'Park Place',
      value: 4,
      color: 'darkblue',
      rentValues: [3, 8],
      maxInSet: 2,
      description: 'Koyu Mavi grubuna ait arsa kartı. Set tamamlandığında 8M kira üretir.',
    },
    category: 'property',
    countInDeck: 1,
    categoryLabelTr: 'Değerli Arsa Kartı',
    categoryLabelEn: 'Luxury Property',
    detailedDescriptionTr: 'Park Place (Yeniköy), Boardwalk ile birleşerek oyundaki en ölümcül mülk ikilisini oluşturur.',
    detailedDescriptionEn: 'Park Place combines with Boardwalk to form the most devastating 2-card rent combo in the game.',
    strategyTipsTr: [
      'Tek başına 4M banka değerine sahiptir, acil durumlarda yüksek ödemeleri tek kartla karşılayabilir.',
      'Koyu Mavi/Yeşil ikili jokeri ile hızlıca tamamlanabilir.'
    ],
    strategyTipsEn: [
      'Has a 4M bank value, capable of covering large single debts in emergencies.',
      'Pairs perfectly with Dark Blue/Green dual wildcards.'
    ],
    counterplayTr: 'Rakibin elinden Sinsi Anlaşma ile Park Place\'i çekip seti bozun.',
    counterplayEn: 'Pluck it away from the opponent with Sly Deal before they pair it.',
    rarity: 'legendary',
  },

  // AÇIK MAVİ (Light Blue)
  {
    id: 'prop-connecticut',
    card: {
      id: 'cat-connecticut',
      type: 'property',
      name: 'Connecticut Avenue',
      value: 1,
      color: 'lightblue',
      rentValues: [1, 2, 3],
      maxInSet: 3,
      description: 'Açık Mavi grubuna ait arsa kartı. Set için 3 kart gerekir.',
    },
    category: 'property',
    countInDeck: 1,
    categoryLabelTr: 'Arsa Mülk Kartı',
    categoryLabelEn: 'Property Deed',
    detailedDescriptionTr: 'Connecticut Avenue (Ortaköy), Açık Mavi renk grubuna aittir. 3 kartla tamamlandığında 3M kira verir.',
    detailedDescriptionEn: 'Connecticut Avenue belongs to the Light Blue group. Full set gives 3M rent.',
    strategyTipsTr: [
      'Açık Mavi seti ucuzdur ve rakipler genellikle Deal Breaker\'larını bu sete harcamak istemez.',
      'Ev ve Otel kurarak 3M kirayı 10M\'e çıkarabilirsiniz.'
    ],
    strategyTipsEn: [
      'Opponents rarely waste their Deal Breakers on cheap Light Blue sets, making it a safe victory pillar.',
      'Add Houses and Hotels to elevate 3M rent to 10M.'
    ],
    counterplayTr: 'Kira kartları gelmeden önce Zoraki Takas ile arsayı takas edin.',
    counterplayEn: 'Force a swap using Forced Deal before rent is charged.',
    rarity: 'common',
  },
  {
    id: 'prop-vermont',
    card: {
      id: 'cat-vermont',
      type: 'property',
      name: 'Vermont Avenue',
      value: 1,
      color: 'lightblue',
      rentValues: [1, 2, 3],
      maxInSet: 3,
      description: 'Açık Mavi grubuna ait arsa kartı. Set için 3 kart gerekir.',
    },
    category: 'property',
    countInDeck: 1,
    categoryLabelTr: 'Arsa Mülk Kartı',
    categoryLabelEn: 'Property Deed',
    detailedDescriptionTr: 'Vermont Avenue (Karaköy), Açık Mavi setin 2. mülküdür.',
    detailedDescriptionEn: 'Vermont Avenue is the second piece in the 3-card Light Blue set.',
    strategyTipsTr: ['Erken safhada masaya indirerek güvenli bir mülk temeli oluşturun.'],
    strategyTipsEn: ['Lay it down early to establish a stable board presence.'],
    counterplayTr: 'Sinsi Anlaşma ile çalın.',
    counterplayEn: 'Steal with Sly Deal.',
    rarity: 'common',
  },
  {
    id: 'prop-oriental',
    card: {
      id: 'cat-oriental',
      type: 'property',
      name: 'Oriental Avenue',
      value: 1,
      color: 'lightblue',
      rentValues: [1, 2, 3],
      maxInSet: 3,
      description: 'Açık Mavi grubuna ait arsa kartı. Set için 3 kart gerekir.',
    },
    category: 'property',
    countInDeck: 1,
    categoryLabelTr: 'Arsa Mülk Kartı',
    categoryLabelEn: 'Property Deed',
    detailedDescriptionTr: 'Oriental Avenue (Eminönü), Açık Mavi seti tamamlayan 3. karttır.',
    detailedDescriptionEn: 'Oriental Avenue completes the Light Blue set.',
    strategyTipsTr: ['Seti bitiren son kart olarak oynandığında anında zafer koşuluna +1 ekler.'],
    strategyTipsEn: ['Playing this as the 3rd piece immediately locks in a completed set.'],
    counterplayTr: 'Sinsi Anlaşma veya Zoraki Takas.',
    counterplayEn: 'Sly Deal or Forced Deal.',
    rarity: 'common',
  },

  // PEMBE (Pink)
  {
    id: 'prop-virginia',
    card: {
      id: 'cat-virginia',
      type: 'property',
      name: 'Virginia Avenue',
      value: 2,
      color: 'pink',
      rentValues: [1, 2, 4],
      maxInSet: 3,
      description: 'Pembe grubuna ait arsa kartı. Tam set olduğunda 4M kira üretir.',
    },
    category: 'property',
    countInDeck: 1,
    categoryLabelTr: 'Arsa Mülk Kartı',
    categoryLabelEn: 'Property Deed',
    detailedDescriptionTr: 'Virginia Avenue (Şişli), Pembe setin üyesidir. Tam seti 4M kira getirisi sağlar.',
    detailedDescriptionEn: 'Virginia Avenue is part of the Pink set with 4M max base rent.',
    strategyTipsTr: ['Pembe set, turuncu ile çift renkli joker ve kira kartlarına sahiptir, sinerjisi yüksektir.'],
    strategyTipsEn: ['Shares dual rent and wildcards with Orange, creating high synergy.'],
    counterplayTr: 'Sinsi Anlaşma ile çalın.',
    counterplayEn: 'Sly Deal.',
    rarity: 'rare',
  },
  {
    id: 'prop-states',
    card: {
      id: 'cat-states',
      type: 'property',
      name: 'States Avenue',
      value: 2,
      color: 'pink',
      rentValues: [1, 2, 4],
      maxInSet: 3,
      description: 'Pembe grubuna ait arsa kartı. Set için 3 kart gerekir.',
    },
    category: 'property',
    countInDeck: 1,
    categoryLabelTr: 'Arsa Mülk Kartı',
    categoryLabelEn: 'Property Deed',
    detailedDescriptionTr: 'States Avenue (Mecidiyeköy), Pembe renk grubunun 2. kartıdır.',
    detailedDescriptionEn: 'States Avenue is the 2nd Pink property deed.',
    strategyTipsTr: ['2M banka değeriyle ortalama bir ödeme güvencesi de sağlar.'],
    strategyTipsEn: ['Provides 2M bank value as backup.'],
    counterplayTr: 'Sly Deal.',
    counterplayEn: 'Sly Deal.',
    rarity: 'rare',
  },
  {
    id: 'prop-stcharles',
    card: {
      id: 'cat-stcharles',
      type: 'property',
      name: 'St. Charles Place',
      value: 2,
      color: 'pink',
      rentValues: [1, 2, 4],
      maxInSet: 3,
      description: 'Pembe grubuna ait arsa kartı. Set için 3 kart gerekir.',
    },
    category: 'property',
    countInDeck: 1,
    categoryLabelTr: 'Arsa Mülk Kartı',
    categoryLabelEn: 'Property Deed',
    detailedDescriptionTr: 'St. Charles Place (Kabataş), Pembe seti tamamlayan 3. karttır.',
    detailedDescriptionEn: 'St. Charles Place completes the Pink set.',
    strategyTipsTr: ['Tamamlandığında Çift Kira ile oynanırsa 8M tahsilat yapar.'],
    strategyTipsEn: ['With Double Rent, full set demands 8M.'],
    counterplayTr: 'Just Say No ile kirayı reddedin.',
    counterplayEn: 'Cancel rent with Just Say No.',
    rarity: 'rare',
  },

  // TURUNCU (Orange)
  {
    id: 'prop-newyork',
    card: {
      id: 'cat-newyork',
      type: 'property',
      name: 'New York Avenue',
      value: 2,
      color: 'orange',
      rentValues: [1, 3, 5],
      maxInSet: 3,
      description: 'Turuncu grubuna ait arsa kartı. Tam set 5M kira üretir.',
    },
    category: 'property',
    countInDeck: 1,
    categoryLabelTr: 'Arsa Mülk Kartı',
    categoryLabelEn: 'Property Deed',
    detailedDescriptionTr: 'New York Avenue (Kadıköy), Turuncu setin en popüler kartlarındandır. Tam set 5M kira getirir.',
    detailedDescriptionEn: 'New York Avenue is a core Orange property offering 5M full set rent.',
    strategyTipsTr: [
      'Turuncu set, orta maliyeti ve yüksek (5M) kira getirisiyle oyundaki en dengeli setlerden biridir.',
      'Ev eklendiğinde 8M, Otel ile 12M kira toplar.'
    ],
    strategyTipsEn: [
      'Orange is considered one of the best sets: reasonable size (3) with high 5M rent.',
      'Add House (8M) and Hotel (12M) for immense board dominance.'
    ],
    counterplayTr: 'Sly Deal veya Deal Breaker.',
    counterplayEn: 'Sly Deal or Deal Breaker.',
    rarity: 'rare',
  },
  {
    id: 'prop-tennessee',
    card: {
      id: 'cat-tennessee',
      type: 'property',
      name: 'Tennessee Avenue',
      value: 2,
      color: 'orange',
      rentValues: [1, 3, 5],
      maxInSet: 3,
      description: 'Turuncu grubuna ait arsa kartı. Set için 3 kart gerekir.',
    },
    category: 'property',
    countInDeck: 1,
    categoryLabelTr: 'Arsa Mülk Kartı',
    categoryLabelEn: 'Property Deed',
    detailedDescriptionTr: 'Tennessee Avenue (Bostancı), Turuncu renk grubunun 2. kartıdır.',
    detailedDescriptionEn: 'Tennessee Avenue is the 2nd Orange property.',
    strategyTipsTr: ['2 kart olduğunda bile 3M kira toplar.'],
    strategyTipsEn: ['2 cards alone generate a solid 3M rent.'],
    counterplayTr: 'Forced Deal ile elinizdeki 1M\'lik değersiz kartla takaslayın.',
    counterplayEn: 'Swap away with Forced Deal.',
    rarity: 'rare',
  },
  {
    id: 'prop-stjames',
    card: {
      id: 'cat-stjames',
      type: 'property',
      name: 'St. James Place',
      value: 2,
      color: 'orange',
      rentValues: [1, 3, 5],
      maxInSet: 3,
      description: 'Turuncu grubuna ait arsa kartı. Set için 3 kart gerekir.',
    },
    category: 'property',
    countInDeck: 1,
    categoryLabelTr: 'Arsa Mülk Kartı',
    categoryLabelEn: 'Property Deed',
    detailedDescriptionTr: 'St. James Place (Moda), Turuncu seti tamamlayan 3. karttır.',
    detailedDescriptionEn: 'St. James Place completes the Orange set.',
    strategyTipsTr: ['Turuncu/Pembe joker kartlarıyla seti hızlıca kapatabilirsiniz.'],
    strategyTipsEn: ['Complete quickly with Orange/Pink wildcards.'],
    counterplayTr: 'Just Say No.',
    counterplayEn: 'Just Say No.',
    rarity: 'rare',
  },

  // KIRMIZI (Red)
  {
    id: 'prop-kentucky',
    card: {
      id: 'cat-kentucky',
      type: 'property',
      name: 'Kentucky Avenue',
      value: 3,
      color: 'red',
      rentValues: [2, 3, 6],
      maxInSet: 3,
      description: 'Kırmızı grubuna ait arsa kartı. Tam set 6M devasa kira üretir.',
    },
    category: 'property',
    countInDeck: 1,
    categoryLabelTr: 'Arsa Mülk Kartı',
    categoryLabelEn: 'Property Deed',
    detailedDescriptionTr: 'Kentucky Avenue (Caddebostan), 3M banka değerine ve 6M tam set kirasına sahip güçlü bir Kırmızı mülktür.',
    detailedDescriptionEn: 'Kentucky Avenue is a high-yield Red property with 6M full set rent.',
    strategyTipsTr: [
      'Kırmızı/Sarı çift kira ve joker kartlarıyla mükemmel uyum sağlar.',
      'Tam set kirası (6M) çift kira ile 12M\'e ulaşır.'
    ],
    strategyTipsEn: [
      'Pairs with Red/Yellow dual rent cards.',
      'Double Rent makes this collect 12M from every opponent.'
    ],
    counterplayTr: 'Deal Breaker.',
    counterplayEn: 'Deal Breaker.',
    rarity: 'rare',
  },
  {
    id: 'prop-indiana',
    card: {
      id: 'cat-indiana',
      type: 'property',
      name: 'Indiana Avenue',
      value: 3,
      color: 'red',
      rentValues: [2, 3, 6],
      maxInSet: 3,
      description: 'Kırmızı grubuna ait arsa kartı. Set için 3 kart gerekir.',
    },
    category: 'property',
    countInDeck: 1,
    categoryLabelTr: 'Arsa Mülk Kartı',
    categoryLabelEn: 'Property Deed',
    detailedDescriptionTr: 'Indiana Avenue (Erenköy), Kırmızı renk grubunun 2. kartıdır.',
    detailedDescriptionEn: 'Indiana Avenue is the 2nd Red property.',
    strategyTipsTr: ['Yüksek banka değeri (3M) sayesinde borç ödemelerinde de güçlüdür.'],
    strategyTipsEn: ['High 3M bank value protects from heavy fees.'],
    counterplayTr: 'Sly Deal.',
    counterplayEn: 'Sly Deal.',
    rarity: 'rare',
  },
  {
    id: 'prop-illinois',
    card: {
      id: 'cat-illinois',
      type: 'property',
      name: 'Illinois Avenue',
      value: 3,
      color: 'red',
      rentValues: [2, 3, 6],
      maxInSet: 3,
      description: 'Kırmızı grubuna ait arsa kartı. Set için 3 kart gerekir.',
    },
    category: 'property',
    countInDeck: 1,
    categoryLabelTr: 'Arsa Mülk Kartı',
    categoryLabelEn: 'Property Deed',
    detailedDescriptionTr: 'Illinois Avenue (Barış Manço), Kırmızı seti tamamlayan 3. karttır.',
    detailedDescriptionEn: 'Illinois Avenue completes the Red set.',
    strategyTipsTr: ['3 kart tamamlandığında masada en çok korkulan kira kaynaklarından biri olur.'],
    strategyTipsEn: ['One of the most feared rent sources when completed.'],
    counterplayTr: 'Deal Breaker ile seti çalın.',
    counterplayEn: 'Steal full set with Deal Breaker.',
    rarity: 'rare',
  },

  // SARI (Yellow)
  {
    id: 'prop-marvin',
    card: {
      id: 'cat-marvin',
      type: 'property',
      name: 'Marvin Gardens',
      value: 3,
      color: 'yellow',
      rentValues: [2, 4, 6],
      maxInSet: 3,
      description: 'Sarı grubuna ait arsa kartı. Tam set 6M kira üretir.',
    },
    category: 'property',
    countInDeck: 1,
    categoryLabelTr: 'Arsa Mülk Kartı',
    categoryLabelEn: 'Property Deed',
    detailedDescriptionTr: 'Marvin Gardens (Teşvikiye), Sarı renk grubunun önde gelen mülküdür. 2 kartta bile 4M kira üretir.',
    detailedDescriptionEn: 'Marvin Gardens generates 4M rent with just 2 cards and 6M at full set.',
    strategyTipsTr: [
      '2 kartta 4M kira üretmesi onu erken safhada çok verimli kılar.',
      'Sarı/Kırmızı ikili jokerleriyle hızlıca tamamlanır.'
    ],
    strategyTipsEn: [
      'Gives 4M rent at just 2 cards, making it an efficient partial set.',
      'Complements Red/Yellow dual wildcards.'
    ],
    counterplayTr: 'Sly Deal.',
    counterplayEn: 'Sly Deal.',
    rarity: 'rare',
  },
  {
    id: 'prop-ventnor',
    card: {
      id: 'cat-ventnor',
      type: 'property',
      name: 'Ventnor Avenue',
      value: 3,
      color: 'yellow',
      rentValues: [2, 4, 6],
      maxInSet: 3,
      description: 'Sarı grubuna ait arsa kartı. Set için 3 kart gerekir.',
    },
    category: 'property',
    countInDeck: 1,
    categoryLabelTr: 'Arsa Mülk Kartı',
    categoryLabelEn: 'Property Deed',
    detailedDescriptionTr: 'Ventnor Avenue (Nişantaşı), Sarı setin 2. mülküdür.',
    detailedDescriptionEn: 'Ventnor Avenue is the 2nd Yellow property deed.',
    strategyTipsTr: ['Set tamamlandığında Ev kurarak 9M kira toplayabilirsiniz.'],
    strategyTipsEn: ['Add a House to collect 9M rent from all players.'],
    counterplayTr: 'Just Say No.',
    counterplayEn: 'Just Say No.',
    rarity: 'rare',
  },
  {
    id: 'prop-atlantic',
    card: {
      id: 'cat-atlantic',
      type: 'property',
      name: 'Atlantic Avenue',
      value: 3,
      color: 'yellow',
      rentValues: [2, 4, 6],
      maxInSet: 3,
      description: 'Sarı grubuna ait arsa kartı. Set için 3 kart gerekir.',
    },
    category: 'property',
    countInDeck: 1,
    categoryLabelTr: 'Arsa Mülk Kartı',
    categoryLabelEn: 'Property Deed',
    detailedDescriptionTr: 'Atlantic Avenue (Beşiktaş), Sarı seti tamamlayan 3. karttır.',
    detailedDescriptionEn: 'Atlantic Avenue completes the Yellow set.',
    strategyTipsTr: ['3 kartla 6M kira toplar.'],
    strategyTipsEn: ['Collects 6M rent with full set.'],
    counterplayTr: 'Deal Breaker.',
    counterplayEn: 'Deal Breaker.',
    rarity: 'rare',
  },

  // YEŞİL (Green)
  {
    id: 'prop-northcarolina',
    card: {
      id: 'cat-northcarolina',
      type: 'property',
      name: 'North Carolina Avenue',
      value: 4,
      color: 'green',
      rentValues: [2, 4, 7],
      maxInSet: 3,
      description: 'Yeşil grubuna ait prestijli arsa kartı. Tam set 7M dev kira getirir.',
    },
    category: 'property',
    countInDeck: 1,
    categoryLabelTr: 'Değerli Arsa Kartı',
    categoryLabelEn: 'Luxury Property',
    detailedDescriptionTr: 'North Carolina Avenue (Levent), 4M değerinde yüksek bütçeli Yeşil mülktür. Tam set 7M kira verir.',
    detailedDescriptionEn: 'North Carolina Avenue is a high-value Green property giving 7M full set rent.',
    strategyTipsTr: [
      'Yeşil/Koyu Mavi ikili kira kartıyla oynandığında masayı silip süpürür.',
      'Yeşil/Demiryolu jokeriyle de tamamlanabilir.'
    ],
    strategyTipsEn: [
      'Dominates when paired with Green/Dark Blue dual rent cards.',
      'Pairs with Green/Railroad wildcard.'
    ],
    counterplayTr: 'Deal Breaker ile tamamlanmış seti çalın.',
    counterplayEn: 'Steal full set with Deal Breaker.',
    rarity: 'epic',
  },
  {
    id: 'prop-pacific',
    card: {
      id: 'cat-pacific',
      type: 'property',
      name: 'Pacific Avenue',
      value: 4,
      color: 'green',
      rentValues: [2, 4, 7],
      maxInSet: 3,
      description: 'Yeşil grubuna ait arsa kartı. Set için 3 kart gerekir.',
    },
    category: 'property',
    countInDeck: 1,
    categoryLabelTr: 'Değerli Arsa Kartı',
    categoryLabelEn: 'Luxury Property',
    detailedDescriptionTr: 'Pacific Avenue (Etiler), Yeşil renk grubunun 2. kartıdır.',
    detailedDescriptionEn: 'Pacific Avenue is the 2nd Green property.',
    strategyTipsTr: ['4M banka değeri borç tahsildarına karşı en sağlam kalkandır.'],
    strategyTipsEn: ['4M bank value shields you against Debt Collector.'],
    counterplayTr: 'Sly Deal.',
    counterplayEn: 'Sly Deal.',
    rarity: 'epic',
  },
  {
    id: 'prop-pennsylvania',
    card: {
      id: 'cat-pennsylvania',
      type: 'property',
      name: 'Pennsylvania Avenue',
      value: 4,
      color: 'green',
      rentValues: [2, 4, 7],
      maxInSet: 3,
      description: 'Yeşil grubuna ait arsa kartı. Set için 3 kart gerekir.',
    },
    category: 'property',
    countInDeck: 1,
    categoryLabelTr: 'Değerli Arsa Kartı',
    categoryLabelEn: 'Luxury Property',
    detailedDescriptionTr: 'Pennsylvania Avenue (Bebek), Yeşil seti tamamlayan 3. karttır.',
    detailedDescriptionEn: 'Pennsylvania Avenue completes the Green set.',
    strategyTipsTr: ['Tam set + Ev + Otel ile tek turda 14M kira toplayabilirsiniz.'],
    strategyTipsEn: ['Full set + House + Hotel achieves 14M rent.'],
    counterplayTr: 'Deal Breaker.',
    counterplayEn: 'Deal Breaker.',
    rarity: 'epic',
  },

  // DEMİRYOLU / İSTASYON (Railroad - 4 Adet)
  {
    id: 'prop-reading-rr',
    card: {
      id: 'cat-reading-rr',
      type: 'property',
      name: 'Reading Railroad',
      value: 2,
      color: 'railroad',
      rentValues: [1, 2, 3, 4],
      maxInSet: 4,
      description: 'Demiryolu grubuna ait kart. 4 istasyonla 4M kira üretir.',
    },
    category: 'property',
    countInDeck: 1,
    categoryLabelTr: 'İstasyon / Demiryolu',
    categoryLabelEn: 'Railroad Deed',
    detailedDescriptionTr: 'Reading Railroad (Haydarpaşa Garı), 4 kartlık Demiryolu setinin ilk parçasıdır.',
    detailedDescriptionEn: 'Reading Railroad is part of the 4-card Railroad set.',
    strategyTipsTr: [
      'Destede çok sayıda Demiryolu jokeri (Kamu/Demiryolu, Açık Mavi/Demiryolu, Yeşil/Demiryolu) bulunur, bu yüzden seti tamamlamak kolaydır.',
      'Her eklenen istasyon kirayı +1M artırır (1M, 2M, 3M, 4M).'
    ],
    strategyTipsEn: [
      'Many dual wildcards include Railroad, making it flexible to assemble.',
      'Scales linearly with each added station: 1M, 2M, 3M, 4M.'
    ],
    counterplayTr: 'Sly Deal.',
    counterplayEn: 'Sly Deal.',
    rarity: 'rare',
  },
  {
    id: 'prop-penn-rr',
    card: {
      id: 'cat-penn-rr',
      type: 'property',
      name: 'Pennsylvania Railroad',
      value: 2,
      color: 'railroad',
      rentValues: [1, 2, 3, 4],
      maxInSet: 4,
      description: 'Demiryolu grubuna ait kart. Set için 4 kart gerekir.',
    },
    category: 'property',
    countInDeck: 1,
    categoryLabelTr: 'İstasyon / Demiryolu',
    categoryLabelEn: 'Railroad Deed',
    detailedDescriptionTr: 'Pennsylvania Railroad (Sirkeci Garı), Demiryolu setinin 2. kartıdır.',
    detailedDescriptionEn: 'Pennsylvania Railroad is the 2nd Railroad deed.',
    strategyTipsTr: ['2 istasyonla 2M kira üretir.'],
    strategyTipsEn: ['Produces 2M rent with 2 stations.'],
    counterplayTr: 'Forced Deal.',
    counterplayEn: 'Forced Deal.',
    rarity: 'rare',
  },
  {
    id: 'prop-bo-rr',
    card: {
      id: 'cat-bo-rr',
      type: 'property',
      name: 'B. & O. Railroad',
      value: 2,
      color: 'railroad',
      rentValues: [1, 2, 3, 4],
      maxInSet: 4,
      description: 'Demiryolu grubuna ait kart. Set için 4 kart gerekir.',
    },
    category: 'property',
    countInDeck: 1,
    categoryLabelTr: 'İstasyon / Demiryolu',
    categoryLabelEn: 'Railroad Deed',
    detailedDescriptionTr: 'B. & O. Railroad (Kadıköy Vapur İskelesi), Demiryolu setinin 3. kartıdır.',
    detailedDescriptionEn: 'B. & O. Railroad is the 3rd Railroad deed.',
    strategyTipsTr: ['3 istasyonla 3M kira toplar.'],
    strategyTipsEn: ['Produces 3M rent with 3 stations.'],
    counterplayTr: 'Sly Deal.',
    counterplayEn: 'Sly Deal.',
    rarity: 'rare',
  },
  {
    id: 'prop-shortline-rr',
    card: {
      id: 'cat-shortline-rr',
      type: 'property',
      name: 'Short Line Railroad',
      value: 2,
      color: 'railroad',
      rentValues: [1, 2, 3, 4],
      maxInSet: 4,
      description: 'Demiryolu grubuna ait kart. Set için 4 kart gerekir.',
    },
    category: 'property',
    countInDeck: 1,
    categoryLabelTr: 'İstasyon / Demiryolu',
    categoryLabelEn: 'Railroad Deed',
    detailedDescriptionTr: 'Short Line Railroad (Yenikapı İskelesi), Demiryolu setini tamamlayan 4. karttır.',
    detailedDescriptionEn: 'Short Line completes the 4-card Railroad set.',
    strategyTipsTr: ['4 istasyonla 4M kira üretir ve zafer için 1 tam set sayılır.'],
    strategyTipsEn: ['4 stations produce 4M rent and count as a completed set.'],
    counterplayTr: 'Deal Breaker.',
    counterplayEn: 'Deal Breaker.',
    rarity: 'rare',
  },

  // KAMU HİZMETİ (Utility - 2 Adet)
  {
    id: 'prop-water-works',
    card: {
      id: 'cat-water-works',
      type: 'property',
      name: 'Water Works',
      value: 2,
      color: 'utility',
      rentValues: [1, 2],
      maxInSet: 2,
      description: 'Kamu Hizmeti grubuna ait kart. Sadece 2 kartla tam set olur.',
    },
    category: 'property',
    countInDeck: 1,
    categoryLabelTr: 'Kamu Hizmeti',
    categoryLabelEn: 'Utility Deed',
    detailedDescriptionTr: 'Water Works (Sular İdaresi), sadece 2 kartla bitirilebilen en hızlı setlerden biridir (1M, 2M kira).',
    detailedDescriptionEn: 'Water Works requires only 2 cards to complete the full Utility set.',
    strategyTipsTr: [
      '2 kartlık kolay tam set sayesinde hızlıca 3 set hedefine ulaşabilirsiniz.',
      'Kamu/Demiryolu jokeriyle tek hamlede tamamlanabilir.'
    ],
    strategyTipsEn: [
      'Easy 2-card completion makes it an ideal fast victory objective.',
      'Instantly completed with a Utility/Railroad wildcard.'
    ],
    counterplayTr: 'Sly Deal ile çalın.',
    counterplayEn: 'Sly Deal.',
    rarity: 'common',
  },
  {
    id: 'prop-electric-company',
    card: {
      id: 'cat-electric-company',
      type: 'property',
      name: 'Electric Company',
      value: 2,
      color: 'utility',
      rentValues: [1, 2],
      maxInSet: 2,
      description: 'Kamu Hizmeti grubuna ait kart. Sadece 2 kartla tam set olur.',
    },
    category: 'property',
    countInDeck: 1,
    categoryLabelTr: 'Kamu Hizmeti',
    categoryLabelEn: 'Utility Deed',
    detailedDescriptionTr: 'Electric Company (Elektrik İdaresi), Kamu Hizmeti setinin diğer yarısıdır.',
    detailedDescriptionEn: 'Electric Company completes the Utility set alongside Water Works.',
    strategyTipsTr: ['Sıranızda hemen masaya indirip seti kapatın.'],
    strategyTipsEn: ['Play immediately to secure a completed set.'],
    counterplayTr: 'Deal Breaker veya Sly Deal.',
    counterplayEn: 'Deal Breaker or Sly Deal.',
    rarity: 'common',
  },

  // ==========================================
  // 2. JOKER KARTLAR (Wildcards - 11 Adet)
  // ==========================================
  {
    id: 'wild-multicolor',
    card: {
      id: 'cat-wild-multi',
      type: 'wildcard',
      name: 'Çok Renkli Joker (Multi-Color Wildcard)',
      value: 4,
      isWildcard: true,
      allowedColors: ['brown', 'lightblue', 'pink', 'orange', 'red', 'yellow', 'green', 'darkblue', 'railroad', 'utility'],
      description: 'Herhangi bir renk grubuna yerleştirilebilen süper joker arsa kartı.',
    },
    category: 'wildcard',
    countInDeck: 2,
    categoryLabelTr: 'Süper Joker Arsa',
    categoryLabelEn: 'Multi-Color Wildcard',
    detailedDescriptionTr: 'Oyundaki en esnek ve güçlü mülk kartıdır. 10 farklı renk grubundan herhangi birine yerleştirilebilir ve sıranızda istediğiniz sete taşınabilir.',
    detailedDescriptionEn: 'The most versatile property card in the game. Can be placed in any of the 10 color groups and rearranged on your turn.',
    strategyTipsTr: [
      'Eksik olan 2 kartlık Koyu Mavi veya Kahverengi setlerinizi anında tamamlamak için kullanın.',
      'Gerektiğinde başka bir sete taşıyarak zafer için 3. tam seti oluşturun.',
      '4M banka değeriyle masada değilken kasaya da atılabilir.'
    ],
    strategyTipsEn: [
      'Use it to instantly complete high-impact 2-card sets like Dark Blue or Brown.',
      'Shift it between sets during your turn to reach the 3 completed sets threshold.',
      'Can be banked for 4M in an emergency.'
    ],
    counterplayTr: 'Sly Deal ile rakip seti tamamlamadan önce bu jokeri kendi alanınıza çalın.',
    counterplayEn: 'Steal it with Sly Deal before the opponent can lock in their set.',
    rarity: 'legendary',
  },
  {
    id: 'wild-darkblue-green',
    card: {
      id: 'cat-wild-darkblue-green',
      type: 'wildcard',
      name: 'Koyu Mavi / Yeşil Joker',
      value: 4,
      color: 'darkblue',
      secondaryColor: 'green',
      allowedColors: ['darkblue', 'green'],
      isWildcard: true,
      description: 'Koyu Mavi veya Yeşil renk grubu olarak kullanılabilen joker arsa kartı.',
    },
    category: 'wildcard',
    countInDeck: 1,
    categoryLabelTr: 'İkili Renk Joker',
    categoryLabelEn: 'Dual-Color Wildcard',
    detailedDescriptionTr: 'Koyu Mavi (8M kira) veya Yeşil (7M kira) setlerinde kullanılabilir. İki en pahalı renk grubunu destekler.',
    detailedDescriptionEn: 'Can be placed in Dark Blue (8M rent) or Green (7M rent) sets.',
    strategyTipsTr: ['Boardwalk veya Park Place ile birleştirerek 2 kartlık Koyu Mavi seti anında bitirin.'],
    strategyTipsEn: ['Pair with Boardwalk or Park Place to complete Dark Blue immediately.'],
    counterplayTr: 'Sly Deal veya Forced Deal.',
    counterplayEn: 'Sly Deal or Forced Deal.',
    rarity: 'epic',
  },
  {
    id: 'wild-lightblue-brown',
    card: {
      id: 'cat-wild-lightblue-brown',
      type: 'wildcard',
      name: 'Açık Mavi / Kahverengi Joker',
      value: 1,
      color: 'lightblue',
      secondaryColor: 'brown',
      allowedColors: ['lightblue', 'brown'],
      isWildcard: true,
      description: 'Açık Mavi veya Kahverengi renk grubu olarak kullanılabilen joker arsa kartı.',
    },
    category: 'wildcard',
    countInDeck: 1,
    categoryLabelTr: 'İkili Renk Joker',
    categoryLabelEn: 'Dual-Color Wildcard',
    detailedDescriptionTr: 'Kahverengi veya Açık Mavi setlerini hızlıca tamamlamak için ideal joker karttır.',
    detailedDescriptionEn: 'Ideal wildcard for quickly completing Brown or Light Blue sets.',
    strategyTipsTr: ['1 kartlık Kahverenginizin yanına koyarak tek hamlede 1. tam setinizi tamamlayın.'],
    strategyTipsEn: ['Drop beside a single Brown property to complete your 1st set in one move.'],
    counterplayTr: 'Sly Deal.',
    counterplayEn: 'Sly Deal.',
    rarity: 'common',
  },
  {
    id: 'wild-orange-pink',
    card: {
      id: 'cat-wild-orange-pink',
      type: 'wildcard',
      name: 'Turuncu / Pembe Joker',
      value: 2,
      color: 'orange',
      secondaryColor: 'pink',
      allowedColors: ['orange', 'pink'],
      isWildcard: true,
      description: 'Turuncu veya Pembe renk grubu olarak kullanılabilen joker arsa kartı.',
    },
    category: 'wildcard',
    countInDeck: 2,
    categoryLabelTr: 'İkili Renk Joker',
    categoryLabelEn: 'Dual-Color Wildcard',
    detailedDescriptionTr: 'Turuncu (5M) veya Pembe (4M) setlerinde kullanılır. Destede 2 adet bulunur.',
    detailedDescriptionEn: 'Fits into Orange (5M) or Pink (4M) sets. 2 copies exist in the deck.',
    strategyTipsTr: ['Turuncu setin 3. kartı olarak kullanıp üzerine kira oynayın.'],
    strategyTipsEn: ['Use as the 3rd Orange piece and trigger Orange rent.'],
    counterplayTr: 'Sly Deal.',
    counterplayEn: 'Sly Deal.',
    rarity: 'rare',
  },
  {
    id: 'wild-yellow-red',
    card: {
      id: 'cat-wild-yellow-red',
      type: 'wildcard',
      name: 'Sarı / Kırmızı Joker',
      value: 3,
      color: 'yellow',
      secondaryColor: 'red',
      allowedColors: ['yellow', 'red'],
      isWildcard: true,
      description: 'Sarı veya Kırmızı renk grubu olarak kullanılabilen joker arsa kartı.',
    },
    category: 'wildcard',
    countInDeck: 2,
    categoryLabelTr: 'İkili Renk Joker',
    categoryLabelEn: 'Dual-Color Wildcard',
    detailedDescriptionTr: 'Sarı (6M) veya Kırmızı (6M) setlerinde kullanılır. Her iki renk de yüksek kira üretir.',
    detailedDescriptionEn: 'Fits into Yellow (6M) or Red (6M) sets. Both are top-tier rent earners.',
    strategyTipsTr: ['Destede 2 adet olduğu için Kırmızı/Sarı taktiklerinde çok etkilidir.'],
    strategyTipsEn: ['With 2 copies in the deck, highly effective for Red/Yellow strategies.'],
    counterplayTr: 'Forced Deal ile takaslayın.',
    counterplayEn: 'Forced Deal.',
    rarity: 'rare',
  },
  {
    id: 'wild-green-railroad',
    card: {
      id: 'cat-wild-green-railroad',
      type: 'wildcard',
      name: 'Yeşil / Demiryolu Joker',
      value: 4,
      color: 'green',
      secondaryColor: 'railroad',
      allowedColors: ['green', 'railroad'],
      isWildcard: true,
      description: 'Yeşil veya Demiryolu renk grubu olarak kullanılabilen joker arsa kartı.',
    },
    category: 'wildcard',
    countInDeck: 1,
    categoryLabelTr: 'İkili Renk Joker',
    categoryLabelEn: 'Dual-Color Wildcard',
    detailedDescriptionTr: 'Yeşil (7M) veya Demiryolu (4M) setlerinde joker olarak yer alır. 4M banka değeri vardır.',
    detailedDescriptionEn: 'Acts as Green (7M) or Railroad (4M). Carries 4M bank value.',
    strategyTipsTr: ['Yeşil sete yerleştirildiğinde 7M kiraya ortak olur.'],
    strategyTipsEn: ['Place into Green for massive 7M rent output.'],
    counterplayTr: 'Sly Deal.',
    counterplayEn: 'Sly Deal.',
    rarity: 'epic',
  },
  {
    id: 'wild-lightblue-railroad',
    card: {
      id: 'cat-wild-lightblue-railroad',
      type: 'wildcard',
      name: 'Açık Mavi / Demiryolu Joker',
      value: 2,
      color: 'lightblue',
      secondaryColor: 'railroad',
      allowedColors: ['lightblue', 'railroad'],
      isWildcard: true,
      description: 'Açık Mavi veya Demiryolu renk grubu olarak kullanılabilen joker arsa kartı.',
    },
    category: 'wildcard',
    countInDeck: 1,
    categoryLabelTr: 'İkili Renk Joker',
    categoryLabelEn: 'Dual-Color Wildcard',
    detailedDescriptionTr: 'Açık Mavi veya Demiryolu setinde kullanılabilir.',
    detailedDescriptionEn: 'Fits into Light Blue or Railroad sets.',
    strategyTipsTr: ['Demiryolu setini 4\'e tamamlamak için joker olarak kullanın.'],
    strategyTipsEn: ['Use to push Railroad to the maximum 4 cards.'],
    counterplayTr: 'Sly Deal.',
    counterplayEn: 'Sly Deal.',
    rarity: 'rare',
  },
  {
    id: 'wild-utility-railroad',
    card: {
      id: 'cat-wild-utility-railroad',
      type: 'wildcard',
      name: 'Kamu Hizmeti / Demiryolu Joker',
      value: 2,
      color: 'utility',
      secondaryColor: 'railroad',
      allowedColors: ['utility', 'railroad'],
      isWildcard: true,
      description: 'Kamu Hizmeti veya Demiryolu renk grubu olarak kullanılabilen joker arsa kartı.',
    },
    category: 'wildcard',
    countInDeck: 1,
    categoryLabelTr: 'İkili Renk Joker',
    categoryLabelEn: 'Dual-Color Wildcard',
    detailedDescriptionTr: 'Kamu Hizmeti (2 kartlık set) veya Demiryolu (4 kartlık set) için jokerdir.',
    detailedDescriptionEn: 'Wildcard for Utility (2-set) or Railroad (4-set).',
    strategyTipsTr: ['Tek bir Kamu Hizmeti kartınız varsa bu kartla seti anında bitirebilirsiniz.'],
    strategyTipsEn: ['Complete Utility set in one action if you hold 1 utility deed.'],
    counterplayTr: 'Sly Deal.',
    counterplayEn: 'Sly Deal.',
    rarity: 'rare',
  },

  // ==========================================
  // 3. AKSİYON KARTLARI (34 Adet)
  // ==========================================
  {
    id: 'action-deal-breaker',
    card: {
      id: 'cat-deal-breaker',
      type: 'action',
      name: 'Anlaşma Bozan (Deal Breaker)',
      value: 5,
      actionType: 'deal-breaker',
      description: 'Başka bir oyuncunun tamamlanmış bir mülk setini (ev ve otelleriyle birlikte) çal.',
    },
    category: 'action',
    countInDeck: 2,
    categoryLabelTr: 'Efsanevi Aksiyon',
    categoryLabelEn: 'Legendary Action',
    detailedDescriptionTr: 'Oyundaki en güçlü karttır. Rakibin tamamlanmış tam bir mülk setini (üzerindeki Ev ve Oteller dahil) çalarak doğrudan kendi alanınıza ekler. Destede sadece 2 adet bulunur!',
    detailedDescriptionEn: 'The most powerful card in the game. Steals an opponent\'s completed set (including Houses and Hotels). Only 2 copies in the entire deck!',
    strategyTipsTr: [
      'Kartı erken harcamayın; rakip 3. sete yaklaştığında veya Koyu Mavi/Yeşil seti bitirdiğinde oynayın.',
      'Rakibin elinde Just Say No olup olmadığını test etmek için önce Sly Deal veya Kira kartıyla yoklayın.',
      'Kendi elinizde de Just Say No varken oynarsanız, rakibin savunmasını da kırarak seti kesin çalarsınız.'
    ],
    strategyTipsEn: [
      'Do not waste this early; wait until an opponent finishes a high-value set (Dark Blue) or is 1 set away from winning.',
      'Bait out the opponent\'s Just Say No with a Sly Deal or Rent card first.',
      'If you have a Just Say No in hand, you can counter their counter, ensuring the steal.'
    ],
    counterplayTr: 'Sadece "Hayır Teşekkürler (Just Say No)" kartı ile anında engellenebilir.',
    counterplayEn: 'Can only be countered with "Just Say No".',
    rarity: 'legendary',
  },
  {
    id: 'action-just-say-no',
    card: {
      id: 'cat-just-say-no',
      type: 'action',
      name: 'Hayır Teşekkürler (Just Say No)',
      value: 4,
      actionType: 'just-say-no',
      description: 'Sana karşı oynanan herhangi bir aksiyon kartını (Deal Breaker, Sly Deal, Kira vb.) anında iptal et.',
    },
    category: 'action',
    countInDeck: 3,
    categoryLabelTr: 'Savunma Aksiyonu',
    categoryLabelEn: 'Counter Action',
    detailedDescriptionTr: 'Sıra sizde olmasa bile oynanabilen nihai savunma kartıdır. Size karşı oynanan Deal Breaker, Sly Deal, Zoraki Takas, Borç Tahsildarı veya Kira taleplerini anında geçersiz kılar.',
    detailedDescriptionEn: 'The ultimate counter card. Can be played out of turn to cancel any action played against you. Destede 3 adet bulunur.',
    strategyTipsTr: [
      'Küçük kira talepleri (1M-2M) için harcamayın; Deal Breaker veya yüksek kira (8M+) saldırılarına saklayın.',
      'Rakip sizin hamlenize Just Say No attığında, siz de ikinci bir Just Say No atarak kendi hamlenizi geçerli kılabilirsiniz (JSN Düellosu)!'
    ],
    strategyTipsEn: [
      'Save for game-deciding plays (Deal Breaker, 8M+ rent) rather than minor 1M debts.',
      'You can chain a Just Say No onto their Just Say No to force your original action through!'
    ],
    counterplayTr: 'Rakibin Just Say No\'suna karşı ikinci bir Just Say No oynayarak karşılık verebilirsiniz.',
    counterplayEn: 'Play your own Just Say No in response to cancel their defense.',
    rarity: 'epic',
  },
  {
    id: 'action-sly-deal',
    card: {
      id: 'cat-sly-deal',
      type: 'action',
      name: 'Sinsi Anlaşma (Sly Deal)',
      value: 3,
      actionType: 'sly-deal',
      description: 'Başka bir oyuncunun tamamlanmamış bir setinden 1 arsa kartı veya joker çal.',
    },
    category: 'action',
    countInDeck: 3,
    categoryLabelTr: 'Hırsızlık Aksiyonu',
    categoryLabelEn: 'Steal Action',
    detailedDescriptionTr: 'Rakibin masadaki tamamlanmamış setinden istediğiniz 1 arsa kartını veya jokeri çalar. Tamamlanmış setlerden kart çalamaz.',
    detailedDescriptionEn: 'Steals 1 property or wildcard from any opponent\'s incomplete set. Cannot steal from completed sets.',
    strategyTipsTr: [
      'Rakibin 2 kartlık Koyu Mavisinden Boardwalk\'u veya Çok Renkli Jokerini çalmak için mükemmeldir.',
      'Rakibin set tamamlamasını engelleyerek zaferini geciktirin.'
    ],
    strategyTipsEn: [
      'Snatch away critical pieces (like Boardwalk or Multi-color Wildcards) before the opponent completes the set.',
      'Great for disrupting opponents sitting on 2/3 cards of a set.'
    ],
    counterplayTr: 'Just Say No ile iptal edin veya setlerinizi hemen tamamlayarak koruma altına alın.',
    counterplayEn: 'Cancel with Just Say No or complete your set immediately to protect it.',
    rarity: 'rare',
  },
  {
    id: 'action-forced-deal',
    card: {
      id: 'cat-forced-deal',
      type: 'action',
      name: 'Zoraki Takas (Forced Deal)',
      value: 3,
      actionType: 'forced-deal',
      description: 'Kendi tamamlanmamış setindeki bir arsayı rakibin tamamlanmamış setindeki bir arsayla zorla takas et.',
    },
    category: 'action',
    countInDeck: 4,
    categoryLabelTr: 'Takas Aksiyonu',
    categoryLabelEn: 'Swap Action',
    detailedDescriptionTr: 'Masadaki 1M\'lik değersiz bir mülkünüzü verip rakibin 4M\'lik değerli mülkünü (Boardwalk vb.) veya eksik set parçanızı zorla almanızı sağlar.',
    detailedDescriptionEn: 'Forces an opponent to trade 1 property from an incomplete set with 1 of yours. Great for giving a 1M card to take a 4M card.',
    strategyTipsTr: [
      '1M\'lik Kahverengi arsayı verip rakibin 4M\'lik Koyu Mavi veya Yeşil arsasını alın (kâr +3M ve set tamamlama).',
      'Destede 4 adet bulunduğu için en sık gelen takas silahıdır.'
    ],
    strategyTipsEn: [
      'Trade your cheap 1M Brown for their 4M Dark Blue/Green property for instant value.',
      'With 4 copies in the deck, it is your most reliable property-fixing tool.'
    ],
    counterplayTr: 'Just Say No ile takası reddedin.',
    counterplayEn: 'Cancel with Just Say No.',
    rarity: 'rare',
  },
  {
    id: 'action-debt-collector',
    card: {
      id: 'cat-debt-collector',
      type: 'action',
      name: 'Borç Tahsildarı (Debt Collector)',
      value: 3,
      actionType: 'debt-collector',
      description: 'Seçtiğin tek bir oyuncudan anında 5M borç talep et.',
    },
    category: 'action',
    countInDeck: 3,
    categoryLabelTr: 'Tahsilat Aksiyonu',
    categoryLabelEn: 'Collection Action',
    detailedDescriptionTr: 'Seçtiğiniz bir rakibi hedef alarak 5M ödeme talep eder. Rakip bankasından veya mülklerinden ödemek zorundadır.',
    detailedDescriptionEn: 'Demands 5M from a single targeted player. The target must pay from their bank or properties.',
    strategyTipsTr: [
      'Bankasında para olmayan oyuncuyu hedef alırsanız, masadaki değerli mülklerini size vermek zorunda kalır!',
      'Rakibin bankasını sıfırlayarak bir sonraki turda çaresiz bırakın.'
    ],
    strategyTipsEn: [
      'Target players with empty banks so they are forced to surrender high-value property cards to you!',
      'Drain opponent cash before playing big rent cards.'
    ],
    counterplayTr: 'Just Say No ile reddedin veya bankanızda 5M nakit bulundurun.',
    counterplayEn: 'Cancel with Just Say No or keep cash in your bank.',
    rarity: 'rare',
  },
  {
    id: 'action-birthday',
    card: {
      id: 'cat-birthday',
      type: 'action',
      name: 'Bugün Benim Doğum Günüm! (It\'s My Birthday)',
      value: 2,
      actionType: 'birthday',
      description: 'Tüm oyunculardan anında 2M doğum günü hediyesi talep et.',
    },
    category: 'action',
    countInDeck: 3,
    categoryLabelTr: 'Toplu Tahsilat',
    categoryLabelEn: 'All-Player Collection',
    detailedDescriptionTr: 'Oyundaki TÜM rakiplerden aynı anda 2M ödeme toplar. 4 kişilik oyunda tek hamlede 6M kazandırır.',
    detailedDescriptionEn: 'Demands 2M from EVERY other player. In a 4-player game, collects 6M in one move.',
    strategyTipsTr: [
      'Çok oyunculu maçlarda (3-4 kişi) muazzam toplu gelir sağlar.',
      'Parası olmayan rakiplerden masadaki arsalarını toplamanıza yarar.'
    ],
    strategyTipsEn: [
      'High total yield in 3-4 player games (up to 6M).',
      'Forces players without cash to pay with properties.'
    ],
    counterplayTr: 'Just Say No.',
    counterplayEn: 'Just Say No.',
    rarity: 'rare',
  },
  {
    id: 'action-pass-go',
    card: {
      id: 'cat-pass-go',
      type: 'action',
      name: 'Başlangıç Noktasından Geç (Pass Go)',
      value: 1,
      actionType: 'pass-go',
      description: 'Desteden ekstra 2 kart çek.',
    },
    category: 'action',
    countInDeck: 10,
    categoryLabelTr: 'Kart Çekme Aksiyonu',
    categoryLabelEn: 'Draw Action',
    detailedDescriptionTr: 'Desteden ekstra 2 kart çekmenizi sağlar. El avantajını ve seçeneklerinizi katlar. Destede en çok bulunan karttır (10 adet).',
    detailedDescriptionEn: 'Draw 2 extra cards from the draw pile. Essential for maintaining hand momentum. Most common card in the deck (10 copies).',
    strategyTipsTr: [
      'Sıranızın 1. hamlesi olarak oynayarak yeni kartları hemen aynı turda kullanma şansı yakalayın.',
      'Destede 10 adet olduğu için elinizde tutmayıp hemen oynamak genellikle en iyi hamledir.'
    ],
    strategyTipsEn: [
      'Play as your 1st action in a turn to draw and use newly acquired cards immediately.',
      'Keep your hand full to maximize strategic options.'
    ],
    counterplayTr: 'Engellenemez.',
    counterplayEn: 'Cannot be countered.',
    rarity: 'common',
  },
  {
    id: 'action-double-rent',
    card: {
      id: 'cat-double-rent',
      type: 'action',
      name: 'Kirayı İkiye Katla (Double the Rent)',
      value: 1,
      actionType: 'double-rent',
      description: 'Bir kira kartıyla birlikte oynandığında kira tutarını 2 katına çıkarır.',
    },
    category: 'action',
    countInDeck: 2,
    categoryLabelTr: 'Güçlendirici Aksiyon',
    categoryLabelEn: 'Multiplier Action',
    detailedDescriptionTr: 'Bir kira kartıyla aynı turda oynandığında istenen kirayı tam 2 katına çıkarır. Örneğin 8M Koyu Mavi kirası 16M olur!',
    detailedDescriptionEn: 'Played in combo with a rent card to double the rent demanded (e.g. 8M Dark Blue becomes 16M!). 2 copies in deck.',
    strategyTipsTr: [
      'Koyu Mavi (8M -> 16M), Yeşil (7M -> 14M) veya Kırmızı/Sarı (6M -> 12M) tam setleriyle birlikte kullanıldığında rakipleri tek turda batırır.',
      'Aynı turda 2 hamle harcar (1. hamle: Double Rent, 2. hamle: Kira kartı).'
    ],
    strategyTipsEn: [
      'Devastating on completed Dark Blue (16M) or Green (14M) sets.',
      'Consumes 2 of your 3 actions for the turn (Double Rent + Rent Card).'
    ],
    counterplayTr: 'Just Say No.',
    counterplayEn: 'Just Say No.',
    rarity: 'epic',
  },
  {
    id: 'action-house',
    card: {
      id: 'cat-house',
      type: 'action',
      name: 'Ev (House)',
      value: 3,
      actionType: 'house',
      description: 'Tamamlanmış bir mülk setine eklenir ve setin kira gelirini +3M artırır. Set başına en fazla 1 ev.',
    },
    category: 'action',
    countInDeck: 3,
    categoryLabelTr: 'Geliştirme Aksiyonu',
    categoryLabelEn: 'Building Action',
    detailedDescriptionTr: 'Tamamlanmış bir arsa setine eklenerek kiranızı kalıcı olarak +3M artırır. İstasyon ve Kamu Hizmeti setlerine eklenemez. Otel kurmak için sette Ev bulunması şarttır.',
    detailedDescriptionEn: 'Adds +3M permanent rent to a completed property set. Cannot be built on Railroads or Utilities. Required before building a Hotel.',
    strategyTipsTr: [
      'Ucuz Kahverengi (2M -> 5M) veya Açık Mavi (3M -> 6M) setlerine kurarak kira tehdidini ikiye katlayın.',
      'Otel kurmanın ön koşuludur.'
    ],
    strategyTipsEn: [
      'Turn cheap Brown sets (2M -> 5M) into dangerous income machines.',
      'Required step to build a Hotel (+4M additional).'
    ],
    counterplayTr: 'Deal Breaker seti Ev ile birlikte çalar!',
    counterplayEn: 'Deal Breaker steals the entire set along with the House!',
    rarity: 'rare',
  },
  {
    id: 'action-hotel',
    card: {
      id: 'cat-hotel',
      type: 'action',
      name: 'Otel (Hotel)',
      value: 4,
      actionType: 'hotel',
      description: 'Evi olan tamamlanmış bir sete eklenir ve kirayı ekstra +4M artırır (Toplam Ev+Otel = +7M).',
    },
    category: 'action',
    countInDeck: 2,
    categoryLabelTr: 'Üst Düzey Geliştirme',
    categoryLabelEn: 'Elite Building',
    detailedDescriptionTr: 'Zaten Evi olan tamamlanmış bir sete eklenir ve kirayı +4M daha artırır. Böylece Ev+Otel toplamda +7M kira katkısı sağlar.',
    detailedDescriptionEn: 'Added onto a completed set that already has a House. Adds +4M more rent (Total +7M rent boost with House+Hotel). 2 copies in deck.',
    strategyTipsTr: [
      'Koyu Mavi setine Ev+Otel kurulduğunda kira 8M\'den 15M\'e (Double Rent ile 30M\'e!) fırlar.',
      '4M banka değeri vardır.'
    ],
    strategyTipsEn: [
      'Makes Dark Blue yield 15M (or 30M with Double Rent!), instantly winning most matches.',
      'Has 4M bank value.'
    ],
    counterplayTr: 'Deal Breaker.',
    counterplayEn: 'Deal Breaker.',
    rarity: 'legendary',
  },

  // ==========================================
  // 4. KİRA KARTLARI (Rent Cards - 13 Adet)
  // ==========================================
  {
    id: 'rent-wild',
    card: {
      id: 'cat-rent-wild',
      type: 'rent',
      name: 'Çok Renkli Kira (Wild Rent)',
      value: 3,
      description: 'Sahip olduğun herhangi bir renk grubu için tüm oyunculardan kira bedeli tahsil et.',
    },
    category: 'rent',
    countInDeck: 3,
    categoryLabelTr: 'Süper Kira Kartı',
    categoryLabelEn: 'Wildcard Rent',
    detailedDescriptionTr: 'Masadaki herhangi bir renk grubunuz için TÜM oyunculardan kira toplar. En esnek kira kartıdır. Destede 3 adet bulunur.',
    detailedDescriptionEn: 'Collect rent for ANY color group you own from all players. Most versatile rent card in the game (3 copies).',
    strategyTipsTr: [
      'Masada en yüksek kira veren mülk grubunuz hangisiyse (Koyu Mavi 8M, Yeşil 7M vb.) onu seçin.',
      'Double Rent kartıyla birleştirilebilir.'
    ],
    strategyTipsEn: [
      'Always target your highest current rent group (Dark Blue 8M, Green 7M).',
      'Can be doubled with Double Rent.'
    ],
    counterplayTr: 'Just Say No ile ödemeyi reddedin.',
    counterplayEn: 'Cancel with Just Say No.',
    rarity: 'epic',
  },
  {
    id: 'rent-green-darkblue',
    card: {
      id: 'cat-rent-green-darkblue',
      type: 'rent',
      name: 'Yeşil / Koyu Mavi Kira',
      value: 1,
      color: 'green',
      secondaryColor: 'darkblue',
      allowedColors: ['green', 'darkblue'],
      description: 'Sahip olduğun Yeşil veya Koyu Mavi grubu için tüm oyunculardan kira tahsil et.',
    },
    category: 'rent',
    countInDeck: 2,
    categoryLabelTr: 'İkili Kira Kartı',
    categoryLabelEn: 'Dual Rent Card',
    detailedDescriptionTr: 'Yeşil (maks 7M) veya Koyu Mavi (maks 8M) mülkleriniz için tüm rakiplerden kira toplar.',
    detailedDescriptionEn: 'Collects rent on Green (up to 7M) or Dark Blue (up to 8M) from all players.',
    strategyTipsTr: ['Oyundaki en yüksek kiralı iki renk grubunu hedefler.'],
    strategyTipsEn: ['Targets the two highest-yield sets in the game.'],
    counterplayTr: 'Just Say No.',
    counterplayEn: 'Just Say No.',
    rarity: 'rare',
  },
  {
    id: 'rent-red-yellow',
    card: {
      id: 'cat-rent-red-yellow',
      type: 'rent',
      name: 'Kırmızı / Sarı Kira',
      value: 1,
      color: 'red',
      secondaryColor: 'yellow',
      allowedColors: ['red', 'yellow'],
      description: 'Sahip olduğun Kırmızı veya Sarı grubu için tüm oyunculardan kira tahsil et.',
    },
    category: 'rent',
    countInDeck: 2,
    categoryLabelTr: 'İkili Kira Kartı',
    categoryLabelEn: 'Dual Rent Card',
    detailedDescriptionTr: 'Kırmızı (maks 6M) veya Sarı (maks 6M) mülkleriniz için kira tahsilatı yapar.',
    detailedDescriptionEn: 'Collects rent on Red (up to 6M) or Yellow (up to 6M).',
    strategyTipsTr: ['Her iki renkte de tam sette 6M tahsilat sağlar.'],
    strategyTipsEn: ['Demands 6M at full set for either color.'],
    counterplayTr: 'Just Say No.',
    counterplayEn: 'Just Say No.',
    rarity: 'rare',
  },
  {
    id: 'rent-orange-pink',
    card: {
      id: 'cat-rent-orange-pink',
      type: 'rent',
      name: 'Turuncu / Pembe Kira',
      value: 1,
      color: 'orange',
      secondaryColor: 'pink',
      allowedColors: ['orange', 'pink'],
      description: 'Sahip olduğun Turuncu veya Pembe grubu için tüm oyunculardan kira tahsil et.',
    },
    category: 'rent',
    countInDeck: 2,
    categoryLabelTr: 'İkili Kira Kartı',
    categoryLabelEn: 'Dual Rent Card',
    detailedDescriptionTr: 'Turuncu (maks 5M) veya Pembe (maks 4M) mülkleriniz için kira tahsilatı yapar.',
    detailedDescriptionEn: 'Collects rent on Orange (up to 5M) or Pink (up to 4M).',
    strategyTipsTr: ['Orta safhada rakiplerin bankasını boşaltmak için mükemmeldir.'],
    strategyTipsEn: ['Perfect mid-game card to drain opponent reserves.'],
    counterplayTr: 'Just Say No.',
    counterplayEn: 'Just Say No.',
    rarity: 'rare',
  },
  {
    id: 'rent-brown-lightblue',
    card: {
      id: 'cat-rent-brown-lightblue',
      type: 'rent',
      name: 'Kahverengi / Açık Mavi Kira',
      value: 1,
      color: 'brown',
      secondaryColor: 'lightblue',
      allowedColors: ['brown', 'lightblue'],
      description: 'Sahip olduğun Kahverengi veya Açık Mavi grubu için tüm oyunculardan kira tahsil et.',
    },
    category: 'rent',
    countInDeck: 2,
    categoryLabelTr: 'İkili Kira Kartı',
    categoryLabelEn: 'Dual Rent Card',
    detailedDescriptionTr: 'Kahverengi (maks 2M) veya Açık Mavi (maks 3M) mülkleriniz için kira tahsilatı yapar.',
    detailedDescriptionEn: 'Collects rent on Brown (up to 2M) or Light Blue (up to 3M).',
    strategyTipsTr: ['Erken safhada hızlıca oynanıp rakiplerden nakit koparır.'],
    strategyTipsEn: ['Great for early-game pressure.'],
    counterplayTr: 'Just Say No.',
    counterplayEn: 'Just Say No.',
    rarity: 'common',
  },
  {
    id: 'rent-utility-railroad',
    card: {
      id: 'cat-rent-utility-railroad',
      type: 'rent',
      name: 'Kamu Hizmeti / Demiryolu Kira',
      value: 1,
      color: 'utility',
      secondaryColor: 'railroad',
      allowedColors: ['utility', 'railroad'],
      description: 'Sahip olduğun Kamu Hizmeti veya Demiryolu grubu için tüm oyunculardan kira tahsil et.',
    },
    category: 'rent',
    countInDeck: 2,
    categoryLabelTr: 'İkili Kira Kartı',
    categoryLabelEn: 'Dual Rent Card',
    detailedDescriptionTr: 'Kamu Hizmeti (maks 2M) veya Demiryolu (maks 4M) mülkleriniz için kira tahsilatı yapar.',
    detailedDescriptionEn: 'Collects rent on Utility (up to 2M) or Railroad (up to 4M).',
    strategyTipsTr: ['4 istasyonunuz varken 4M kira üretir.'],
    strategyTipsEn: ['Collects 4M with 4 active railroads.'],
    counterplayTr: 'Just Say No.',
    counterplayEn: 'Just Say No.',
    rarity: 'common',
  },

  // ==========================================
  // 5. PARA KARTLARI (Money Cards - 20 Adet)
  // ==========================================
  {
    id: 'money-10m',
    card: {
      id: 'cat-money-10m',
      type: 'money',
      name: '10M Nakit Para',
      value: 10,
      description: 'Banka kasasına 10 Milyon değerinde para ekler.',
    },
    category: 'money',
    countInDeck: 1,
    categoryLabelTr: 'Efsanevi Nakit',
    categoryLabelEn: 'Jackpot Cash',
    detailedDescriptionTr: 'Oyundaki en yüksek değerli tek para kartıdır. Bankanıza 10M nakit kazandırır ve tüm kira/borç taleplerine karşı devasa bir kalkan oluşturur. Destede sadece 1 adet vardır!',
    detailedDescriptionEn: 'The highest single currency card in the game (10M). Protects your entire property empire from debts. Only 1 exists in the deck!',
    strategyTipsTr: [
      'Hemen bankaya yatırın; elinizde kalırsa rakip Borç Tahsildarı oynadığında elinizdeki kartları kullanamazsınız (ödemeler sadece bankadan veya masadaki mülklerden yapılır).',
      '10M bankadayken hiçbir kira veya borç mülklerinizi kaybetmenize yol açmaz.'
    ],
    strategyTipsEn: [
      'Deposit into your bank immediately so it protects your board from incoming debts.',
      'With 10M banked, opponents cannot easily force you to surrender property deeds.'
    ],
    counterplayTr: 'Borç Tahsildarı veya yüksek kira ile rakibin bankasından çekin.',
    counterplayEn: 'Drain it from their bank with Debt Collector or big rent demands.',
    rarity: 'legendary',
  },
  {
    id: 'money-5m',
    card: {
      id: 'cat-money-5m',
      type: 'money',
      name: '5M Nakit Para',
      value: 5,
      description: 'Banka kasasına 5 Milyon değerinde para ekler.',
    },
    category: 'money',
    countInDeck: 2,
    categoryLabelTr: 'Değerli Nakit',
    categoryLabelEn: 'High-Value Cash',
    detailedDescriptionTr: '5M değerinde sağlam bir nakit rezervidir. Borç Tahsildarı (5M) talebini tek kartla karşılar. Destede 2 adet bulunur.',
    detailedDescriptionEn: 'Solid 5M cash reserve. Covers a full Debt Collector (5M) in a single card. 2 copies in deck.',
    strategyTipsTr: ['Borç Tahsildarı saldırısına karşı tam koruma sağlar.'],
    strategyTipsEn: ['Exact coverage for a 5M Debt Collector demand.'],
    counterplayTr: 'Borç Tahsildarı.',
    counterplayEn: 'Debt Collector.',
    rarity: 'epic',
  },
  {
    id: 'money-4m',
    card: {
      id: 'cat-money-4m',
      type: 'money',
      name: '4M Nakit Para',
      value: 4,
      description: 'Banka kasasına 4 Milyon değerinde para ekler.',
    },
    category: 'money',
    countInDeck: 3,
    categoryLabelTr: 'Nakit Para',
    categoryLabelEn: 'Cash Money',
    detailedDescriptionTr: '4M değerinde para kartı. Destede 3 adet bulunur.',
    detailedDescriptionEn: '4M cash card. 3 copies in deck.',
    strategyTipsTr: ['Bankanızı güçlendirmek için ilk turlarda kasaya atın.'],
    strategyTipsEn: ['Deposit into your bank in early turns.'],
    counterplayTr: 'Kira ve borç kartları.',
    counterplayEn: 'Rent and debt cards.',
    rarity: 'rare',
  },
  {
    id: 'money-3m',
    card: {
      id: 'cat-money-3m',
      type: 'money',
      name: '3M Nakit Para',
      value: 3,
      description: 'Banka kasasına 3 Milyon değerinde para ekler.',
    },
    category: 'money',
    countInDeck: 3,
    categoryLabelTr: 'Nakit Para',
    categoryLabelEn: 'Cash Money',
    detailedDescriptionTr: '3M değerinde para kartı. Destede 3 adet bulunur.',
    detailedDescriptionEn: '3M cash card. 3 copies in deck.',
    strategyTipsTr: ['Orta seviye kira ödemelerini karşılamak için idealdir.'],
    strategyTipsEn: ['Great for paying mid-tier rent without losing properties.'],
    counterplayTr: 'Kira talepleri.',
    counterplayEn: 'Rent demands.',
    rarity: 'common',
  },
  {
    id: 'money-2m',
    card: {
      id: 'cat-money-2m',
      type: 'money',
      name: '2M Nakit Para',
      value: 2,
      description: 'Banka kasasına 2 Milyon değerinde para ekler.',
    },
    category: 'money',
    countInDeck: 5,
    categoryLabelTr: 'Nakit Para',
    categoryLabelEn: 'Cash Money',
    detailedDescriptionTr: '2M değerinde para kartı. Doğum Günü (2M) ödemelerini karşılar. Destede 5 adet bulunur.',
    detailedDescriptionEn: '2M cash card. Exactly covers It\'s My Birthday (2M). 5 copies in deck.',
    strategyTipsTr: ['Doğum günü ödemelerini mülk vermeden karşılamanızı sağlar.'],
    strategyTipsEn: ['Pay Birthday demands cleanly without sacrificing deeds.'],
    counterplayTr: 'Doğum Günü ve Kira kartları.',
    counterplayEn: 'Birthday & Rent cards.',
    rarity: 'common',
  },
  {
    id: 'money-1m',
    card: {
      id: 'cat-money-1m',
      type: 'money',
      name: '1M Nakit Para',
      value: 1,
      description: 'Banka kasasına 1 Milyon değerinde para ekler.',
    },
    category: 'money',
    countInDeck: 6,
    categoryLabelTr: 'Küçük Nakit',
    categoryLabelEn: 'Small Cash',
    detailedDescriptionTr: '1M değerinde temel para kartı. Destede en çok bulunan para türüdür (6 adet).',
    detailedDescriptionEn: '1M base currency. Most numerous cash card in the deck (6 copies).',
    strategyTipsTr: ['Küçük kira ödemelerinde para üstü kaybetmemek için bozuk para görevi görür.'],
    strategyTipsEn: ['Acts as small change to prevent overpaying on low rents.'],
    counterplayTr: 'Küçük kira talepleri.',
    counterplayEn: 'Low rents.',
    rarity: 'common',
  },
];

export const DECK_STATS = {
  totalCards: 106,
  propertyCards: 28,
  wildcardCards: 11,
  actionCards: 34,
  rentCards: 13,
  moneyCards: 20,
};
